apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sitemon
  name: sitemon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sitemon
  template:
    metadata:
      labels:
        app: sitemon
    spec:
      containers:
      - image: alexisv914/sitemon:0.1
        imagePullPolicy: Always
        name: sitemon
        env:
        - name: "SITEMON_METRICSPORT"
          value: "8000"
        - name: "SITEMON_URLS"
          value: "https://httpstat.us/503,https://httpstat.us/200"
        - name: "SITEMON_INTERVAL"
          value: "60"
---
kind: Service
apiVersion: v1
metadata:
  name: sitemon-service
spec:
  selector:
    app: sitemon
  ports:
  # Default port used by the image
  - port: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sitemon-ingress
spec:
  defaultBackend:
    service:
      name: sitemon-service
      port:
        number: 8000
---
