apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sitemon
  name: sitemon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sitemon
  template:
    metadata:
      labels:
        app: sitemon
    spec:
      containers:
      - image: alexisv914/sitemon:0.1
        imagePullPolicy: Always
        name: sitemon
        env:
        - name: "SITEMON_METRICSPORT"
          value: "8000"
        - name: "SITEMON_URLS"
          value: "https://httpstat.us/503,https://httpstat.us/200"
        - name: "SITEMON_INTERVAL"
          value: "60"
